base: &base
  adapter: postgresql
  encoding: unicode
  username: expenseman
  password: eman
  host: localhost
  port: 5432

development:
  <<: *base
  database: expensemanager
  pool: 5

test:
  <<: *base
  database: expensemanager_test
  pool: 5
